# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main  # Change this to the appropriate branch

pr:
- '*'

pool:
  name: LocalContainer  # Replace with the name of your self-hosted agent pool
  demands:
    - msbuild
    - visualstudio

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.artifactstagingdirectory)/$(Build.DefinitionName)'

jobs:
- job: BuildAndTest
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.1.x'  # Change to the .NET Core 2.1 version

  - script: cd BookStore-master/BookStore
    displayName: 'move to working directory'
    
  - script: cd BookStore-master/BookStore
      dotnet restore
    displayName: 'Restore dependencies'

  - script: cd BookStore-master/BookStore 
      dotnet build --configuration $(buildConfiguration) --output $(outputDirectory)
    displayName: 'Build'

  - script: cd BookStore-master/BookStore 
      dotnet test --configuration $(buildConfiguration) --collect "Code coverage"
    displayName: 'Run tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(outputDirectory)'
      Contents: '**/*.dll'
      TargetFolder: '$(build.artifactstagingdirectory)'



